apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: default
spec:
  project: default   
  source:
    repoURL: https://github.com/TopeAU/ArgoCD.git
    targetRevision: HEAD
    path: nginx
    helm:
      ValuesFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
