apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rcidr
  namespace: argocd
spec:
  project: default   
  source:
    repoURL: https://github.com/TopeAU/ArgoCD.git
    targetRevision: HEAD
    path: stage
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
